### ISSUE TITLE
IPipeReader,IPipeWriter,IPipe version error

### ISSUE THREAD

**Issue by ghost** [StackExchange/Channels.WebSockets#6]
i build this project use myget
but  IPipeReader,IPipeWriter,IPipe version error
“IPipe”lost“Reading”
“IPipeWriter”lost“Writing”
“IPipeReader”lost“Reading”

Which version should I use， thanks

**Comment by mgravell** [comment]
you're absolutely right, and that API change has also been a blocker for me
moving this code forward. Maybe @davidfowl knows the status of that?

**Comment by ghost** [comment]
got it.  Thanks. 
By the netgain as game gate.but it don't support net core
So I find this repo.

**Comment by mgravell** [comment]
@cathy33  indeed - this is the moral successor to netgain, but is based on experimental in-flight technologies; it has not yet been updated to the current API surface, because when I tried it couldn't complete due to missing APIs. I'm sure it will get there in time - but at the moment this should be considered an incomplete experiment.

**Comment by davidfowl** [comment]
Right, the timeline for pipelines is the 2.1 .NET Core release. There are still quite a few API changes coming so we can decide if we want to use this library to help give feedback, or we could wait it out.

**Comment by davidfowl** [comment]
Oh, another huge thing that would help this is that we decoupled the http parser from kestrel so that could be used here instead of writing anything custom. It's also already pipelines based.

**Comment by mgravell** [comment]
@davidfowl  so: if I try to ringfence some time to pick this back up and have another stab - should I be playing with the kestrel code, or the separate lib code? which is going to be most useful?

**Comment by davidfowl** [comment]
I think you want to use pieces of kestrel (transport and http parser in particular) without using ASP.NET itself. That will prove that what we have is good. See an example here for using the raw APIs in kestrel (these are subject to change of course):

https://github.com/davidfowl/PlatformLevelTechempower

I would start there and then migrate to the 2.1 APIs from myget. I can help set a frame up if you want 😄

**Comment by ghost** [comment]
Thank you for answering my questions.
